export const afterfireSounds = {
    single: [
      "01_Single_EQ1",
      "box4_01>single",
      "i4_01>single",
      "i5_01>single",
      "i6_01>single",
      "v6_01>single",
      "v6_01>muffled>race_single",
      "v8_crossflow_02>muffled>stock_single",
      "v8_crossflow_02>muffled>race_single",
      "v8_crossflow_03>single",
      "td27_01>single",
    ],
    multi: [
      "01_Multi_EQ1",
      "box4_01>multi",
      "i4_01>multi",
      "i5_01>multi",
      "i6_01>multi",
      "v6_01>multi",
      "v6_01>muffled>race_multi",
      "v8_crossflow_02>muffled>stock_multi",
      "v8_crossflow_02>muffled>race_multi",
      "v8_crossflow_03>multi",
      "td27_01>multi",
    ],
    shift: [
      "01_Shift_EQ1",
      "box4_01>shift",
      "box4_01>shift_dct",
      "i4_01>shift",
      "i4_01>shift_dct",
      "i5_01>shift",
      "i5_01>shift_dct",
      "i5_01>dct_timeline>race_shift_dct",
      "i5_01>dct_timeline>stock_shift_dct",
      "i5_01>dct_timeline>tuned_shift_dct",
      "i6_01>shift",
      "v6_01>shift",
      "v6_01>muffled>race_shift",
      "v8_crossflow_02>muffled>stock_shift",
      "v8_crossflow_02>muffled>race_shift",
      "v8_crossflow_03>shift",
      "td27_01>shift",
    ]
  };
  